# Generated by Django 4.2.1 on 2023-06-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField()),
                ('content', models.CharField(max_length=50)),
                ('dueTo', models.DateTimeField()),
                ('createdAt', models.DateTimeField()),
            ],
        ),
    ]
